/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as PrdsRouteImport } from './routes/prds'
import { Route as HpanelRouteImport } from './routes/hpanel'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillsIndexRouteImport } from './routes/skills.index'
import { Route as HpanelIndexRouteImport } from './routes/hpanel.index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as PromptSlugRouteImport } from './routes/prompt.$slug'
import { Route as PrdSlugRouteImport } from './routes/prd.$slug'
import { Route as HpanelSubmissionsRouteImport } from './routes/hpanel.submissions'
import { Route as HpanelSkillsRouteImport } from './routes/hpanel.skills'
import { Route as HpanelSettingsRouteImport } from './routes/hpanel.settings'
import { Route as HpanelReposRouteImport } from './routes/hpanel.repos'
import { Route as HpanelPromptsRouteImport } from './routes/hpanel.prompts'
import { Route as HpanelPromptCategoriesRouteImport } from './routes/hpanel.prompt-categories'
import { Route as HpanelPrdsRouteImport } from './routes/hpanel.prds'
import { Route as HpanelPrdCategoriesRouteImport } from './routes/hpanel.prd-categories'
import { Route as HpanelOwnersRouteImport } from './routes/hpanel.owners'
import { Route as HpanelImportRouteImport } from './routes/hpanel.import'
import { Route as HpanelDocsRouteImport } from './routes/hpanel.docs'
import { Route as HpanelCategoriesRouteImport } from './routes/hpanel.categories'
import { Route as HpanelAddRouteImport } from './routes/hpanel.add'
import { Route as DocsWhatAreSkillsRouteImport } from './routes/docs.what-are-skills'
import { Route as DocsSpecificationRouteImport } from './routes/docs.specification'
import { Route as DocsIntegrateRouteImport } from './routes/docs.integrate'
import { Route as DocsCreateRouteImport } from './routes/docs.create'
import { Route as SkillsOwnerIndexRouteImport } from './routes/skills.$owner.index'
import { Route as SkillsLegacySkillIdRouteImport } from './routes/skills.legacy.$skillId'
import { Route as HpanelSkillGithubExtractorRouteImport } from './routes/hpanel.skill.github-extractor'
import { Route as SkillsOwnerRepoIndexRouteImport } from './routes/skills.$owner.$repo.index'
import { Route as SkillsOwnerRepoSkillSlugRouteImport } from './routes/skills.$owner.$repo.$skillSlug'

const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const PrdsRoute = PrdsRouteImport.update({
  id: '/prds',
  path: '/prds',
  getParentRoute: () => rootRouteImport,
} as any)
const HpanelRoute = HpanelRouteImport.update({
  id: '/hpanel',
  path: '/hpanel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const HpanelIndexRoute = HpanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HpanelRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptSlugRoute = PromptSlugRouteImport.update({
  id: '/prompt/$slug',
  path: '/prompt/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PrdSlugRoute = PrdSlugRouteImport.update({
  id: '/prd/$slug',
  path: '/prd/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HpanelSubmissionsRoute = HpanelSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => HpanelRoute,
} as any)
const HpanelSkillsRoute = HpanelSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => HpanelRoute,
} as any)
const HpanelSettingsRoute = HpanelSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => HpanelRoute,
} as any)
const HpanelReposRoute = HpanelReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => HpanelRoute,
} as any)
const HpanelPromptsRoute = HpanelPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => HpanelRoute,
} as any)
const HpanelPromptCategoriesRoute = HpanelPromptCategoriesRouteImport.update({
  id: '/prompt-categories',
  path: '/prompt-categories',
  getParentRoute: () => HpanelRoute,
} as any)
const HpanelPrdsRoute = HpanelPrdsRouteImport.update({
  id: '/prds',
  path: '/prds',
  getParentRoute: () => HpanelRoute,
} as any)
const HpanelPrdCategoriesRoute = HpanelPrdCategoriesRouteImport.update({
  id: '/prd-categories',
  path: '/prd-categories',
  getParentRoute: () => HpanelRoute,
} as any)
const HpanelOwnersRoute = HpanelOwnersRouteImport.update({
  id: '/owners',
  path: '/owners',
  getParentRoute: () => HpanelRoute,
} as any)
const HpanelImportRoute = HpanelImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => HpanelRoute,
} as any)
const HpanelDocsRoute = HpanelDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => HpanelRoute,
} as any)
const HpanelCategoriesRoute = HpanelCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => HpanelRoute,
} as any)
const HpanelAddRoute = HpanelAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => HpanelRoute,
} as any)
const DocsWhatAreSkillsRoute = DocsWhatAreSkillsRouteImport.update({
  id: '/docs/what-are-skills',
  path: '/docs/what-are-skills',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSpecificationRoute = DocsSpecificationRouteImport.update({
  id: '/docs/specification',
  path: '/docs/specification',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIntegrateRoute = DocsIntegrateRouteImport.update({
  id: '/docs/integrate',
  path: '/docs/integrate',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsCreateRoute = DocsCreateRouteImport.update({
  id: '/docs/create',
  path: '/docs/create',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsOwnerIndexRoute = SkillsOwnerIndexRouteImport.update({
  id: '/skills/$owner/',
  path: '/skills/$owner/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsLegacySkillIdRoute = SkillsLegacySkillIdRouteImport.update({
  id: '/skills/legacy/$skillId',
  path: '/skills/legacy/$skillId',
  getParentRoute: () => rootRouteImport,
} as any)
const HpanelSkillGithubExtractorRoute =
  HpanelSkillGithubExtractorRouteImport.update({
    id: '/skill/github-extractor',
    path: '/skill/github-extractor',
    getParentRoute: () => HpanelRoute,
  } as any)
const SkillsOwnerRepoIndexRoute = SkillsOwnerRepoIndexRouteImport.update({
  id: '/skills/$owner/$repo/',
  path: '/skills/$owner/$repo/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsOwnerRepoSkillSlugRoute =
  SkillsOwnerRepoSkillSlugRouteImport.update({
    id: '/skills/$owner/$repo/$skillSlug',
    path: '/skills/$owner/$repo/$skillSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hpanel': typeof HpanelRouteWithChildren
  '/prds': typeof PrdsRoute
  '/prompts': typeof PromptsRoute
  '/submit': typeof SubmitRoute
  '/docs/create': typeof DocsCreateRoute
  '/docs/integrate': typeof DocsIntegrateRoute
  '/docs/specification': typeof DocsSpecificationRoute
  '/docs/what-are-skills': typeof DocsWhatAreSkillsRoute
  '/hpanel/add': typeof HpanelAddRoute
  '/hpanel/categories': typeof HpanelCategoriesRoute
  '/hpanel/docs': typeof HpanelDocsRoute
  '/hpanel/import': typeof HpanelImportRoute
  '/hpanel/owners': typeof HpanelOwnersRoute
  '/hpanel/prd-categories': typeof HpanelPrdCategoriesRoute
  '/hpanel/prds': typeof HpanelPrdsRoute
  '/hpanel/prompt-categories': typeof HpanelPromptCategoriesRoute
  '/hpanel/prompts': typeof HpanelPromptsRoute
  '/hpanel/repos': typeof HpanelReposRoute
  '/hpanel/settings': typeof HpanelSettingsRoute
  '/hpanel/skills': typeof HpanelSkillsRoute
  '/hpanel/submissions': typeof HpanelSubmissionsRoute
  '/prd/$slug': typeof PrdSlugRoute
  '/prompt/$slug': typeof PromptSlugRoute
  '/docs/': typeof DocsIndexRoute
  '/hpanel/': typeof HpanelIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/hpanel/skill/github-extractor': typeof HpanelSkillGithubExtractorRoute
  '/skills/legacy/$skillId': typeof SkillsLegacySkillIdRoute
  '/skills/$owner/': typeof SkillsOwnerIndexRoute
  '/skills/$owner/$repo/$skillSlug': typeof SkillsOwnerRepoSkillSlugRoute
  '/skills/$owner/$repo/': typeof SkillsOwnerRepoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prds': typeof PrdsRoute
  '/prompts': typeof PromptsRoute
  '/submit': typeof SubmitRoute
  '/docs/create': typeof DocsCreateRoute
  '/docs/integrate': typeof DocsIntegrateRoute
  '/docs/specification': typeof DocsSpecificationRoute
  '/docs/what-are-skills': typeof DocsWhatAreSkillsRoute
  '/hpanel/add': typeof HpanelAddRoute
  '/hpanel/categories': typeof HpanelCategoriesRoute
  '/hpanel/docs': typeof HpanelDocsRoute
  '/hpanel/import': typeof HpanelImportRoute
  '/hpanel/owners': typeof HpanelOwnersRoute
  '/hpanel/prd-categories': typeof HpanelPrdCategoriesRoute
  '/hpanel/prds': typeof HpanelPrdsRoute
  '/hpanel/prompt-categories': typeof HpanelPromptCategoriesRoute
  '/hpanel/prompts': typeof HpanelPromptsRoute
  '/hpanel/repos': typeof HpanelReposRoute
  '/hpanel/settings': typeof HpanelSettingsRoute
  '/hpanel/skills': typeof HpanelSkillsRoute
  '/hpanel/submissions': typeof HpanelSubmissionsRoute
  '/prd/$slug': typeof PrdSlugRoute
  '/prompt/$slug': typeof PromptSlugRoute
  '/docs': typeof DocsIndexRoute
  '/hpanel': typeof HpanelIndexRoute
  '/skills': typeof SkillsIndexRoute
  '/hpanel/skill/github-extractor': typeof HpanelSkillGithubExtractorRoute
  '/skills/legacy/$skillId': typeof SkillsLegacySkillIdRoute
  '/skills/$owner': typeof SkillsOwnerIndexRoute
  '/skills/$owner/$repo/$skillSlug': typeof SkillsOwnerRepoSkillSlugRoute
  '/skills/$owner/$repo': typeof SkillsOwnerRepoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hpanel': typeof HpanelRouteWithChildren
  '/prds': typeof PrdsRoute
  '/prompts': typeof PromptsRoute
  '/submit': typeof SubmitRoute
  '/docs/create': typeof DocsCreateRoute
  '/docs/integrate': typeof DocsIntegrateRoute
  '/docs/specification': typeof DocsSpecificationRoute
  '/docs/what-are-skills': typeof DocsWhatAreSkillsRoute
  '/hpanel/add': typeof HpanelAddRoute
  '/hpanel/categories': typeof HpanelCategoriesRoute
  '/hpanel/docs': typeof HpanelDocsRoute
  '/hpanel/import': typeof HpanelImportRoute
  '/hpanel/owners': typeof HpanelOwnersRoute
  '/hpanel/prd-categories': typeof HpanelPrdCategoriesRoute
  '/hpanel/prds': typeof HpanelPrdsRoute
  '/hpanel/prompt-categories': typeof HpanelPromptCategoriesRoute
  '/hpanel/prompts': typeof HpanelPromptsRoute
  '/hpanel/repos': typeof HpanelReposRoute
  '/hpanel/settings': typeof HpanelSettingsRoute
  '/hpanel/skills': typeof HpanelSkillsRoute
  '/hpanel/submissions': typeof HpanelSubmissionsRoute
  '/prd/$slug': typeof PrdSlugRoute
  '/prompt/$slug': typeof PromptSlugRoute
  '/docs/': typeof DocsIndexRoute
  '/hpanel/': typeof HpanelIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/hpanel/skill/github-extractor': typeof HpanelSkillGithubExtractorRoute
  '/skills/legacy/$skillId': typeof SkillsLegacySkillIdRoute
  '/skills/$owner/': typeof SkillsOwnerIndexRoute
  '/skills/$owner/$repo/$skillSlug': typeof SkillsOwnerRepoSkillSlugRoute
  '/skills/$owner/$repo/': typeof SkillsOwnerRepoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hpanel'
    | '/prds'
    | '/prompts'
    | '/submit'
    | '/docs/create'
    | '/docs/integrate'
    | '/docs/specification'
    | '/docs/what-are-skills'
    | '/hpanel/add'
    | '/hpanel/categories'
    | '/hpanel/docs'
    | '/hpanel/import'
    | '/hpanel/owners'
    | '/hpanel/prd-categories'
    | '/hpanel/prds'
    | '/hpanel/prompt-categories'
    | '/hpanel/prompts'
    | '/hpanel/repos'
    | '/hpanel/settings'
    | '/hpanel/skills'
    | '/hpanel/submissions'
    | '/prd/$slug'
    | '/prompt/$slug'
    | '/docs/'
    | '/hpanel/'
    | '/skills/'
    | '/hpanel/skill/github-extractor'
    | '/skills/legacy/$skillId'
    | '/skills/$owner/'
    | '/skills/$owner/$repo/$skillSlug'
    | '/skills/$owner/$repo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/prds'
    | '/prompts'
    | '/submit'
    | '/docs/create'
    | '/docs/integrate'
    | '/docs/specification'
    | '/docs/what-are-skills'
    | '/hpanel/add'
    | '/hpanel/categories'
    | '/hpanel/docs'
    | '/hpanel/import'
    | '/hpanel/owners'
    | '/hpanel/prd-categories'
    | '/hpanel/prds'
    | '/hpanel/prompt-categories'
    | '/hpanel/prompts'
    | '/hpanel/repos'
    | '/hpanel/settings'
    | '/hpanel/skills'
    | '/hpanel/submissions'
    | '/prd/$slug'
    | '/prompt/$slug'
    | '/docs'
    | '/hpanel'
    | '/skills'
    | '/hpanel/skill/github-extractor'
    | '/skills/legacy/$skillId'
    | '/skills/$owner'
    | '/skills/$owner/$repo/$skillSlug'
    | '/skills/$owner/$repo'
  id:
    | '__root__'
    | '/'
    | '/hpanel'
    | '/prds'
    | '/prompts'
    | '/submit'
    | '/docs/create'
    | '/docs/integrate'
    | '/docs/specification'
    | '/docs/what-are-skills'
    | '/hpanel/add'
    | '/hpanel/categories'
    | '/hpanel/docs'
    | '/hpanel/import'
    | '/hpanel/owners'
    | '/hpanel/prd-categories'
    | '/hpanel/prds'
    | '/hpanel/prompt-categories'
    | '/hpanel/prompts'
    | '/hpanel/repos'
    | '/hpanel/settings'
    | '/hpanel/skills'
    | '/hpanel/submissions'
    | '/prd/$slug'
    | '/prompt/$slug'
    | '/docs/'
    | '/hpanel/'
    | '/skills/'
    | '/hpanel/skill/github-extractor'
    | '/skills/legacy/$skillId'
    | '/skills/$owner/'
    | '/skills/$owner/$repo/$skillSlug'
    | '/skills/$owner/$repo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HpanelRoute: typeof HpanelRouteWithChildren
  PrdsRoute: typeof PrdsRoute
  PromptsRoute: typeof PromptsRoute
  SubmitRoute: typeof SubmitRoute
  DocsCreateRoute: typeof DocsCreateRoute
  DocsIntegrateRoute: typeof DocsIntegrateRoute
  DocsSpecificationRoute: typeof DocsSpecificationRoute
  DocsWhatAreSkillsRoute: typeof DocsWhatAreSkillsRoute
  PrdSlugRoute: typeof PrdSlugRoute
  PromptSlugRoute: typeof PromptSlugRoute
  DocsIndexRoute: typeof DocsIndexRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
  SkillsLegacySkillIdRoute: typeof SkillsLegacySkillIdRoute
  SkillsOwnerIndexRoute: typeof SkillsOwnerIndexRoute
  SkillsOwnerRepoSkillSlugRoute: typeof SkillsOwnerRepoSkillSlugRoute
  SkillsOwnerRepoIndexRoute: typeof SkillsOwnerRepoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prds': {
      id: '/prds'
      path: '/prds'
      fullPath: '/prds'
      preLoaderRoute: typeof PrdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hpanel': {
      id: '/hpanel'
      path: '/hpanel'
      fullPath: '/hpanel'
      preLoaderRoute: typeof HpanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hpanel/': {
      id: '/hpanel/'
      path: '/'
      fullPath: '/hpanel/'
      preLoaderRoute: typeof HpanelIndexRouteImport
      parentRoute: typeof HpanelRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt/$slug': {
      id: '/prompt/$slug'
      path: '/prompt/$slug'
      fullPath: '/prompt/$slug'
      preLoaderRoute: typeof PromptSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prd/$slug': {
      id: '/prd/$slug'
      path: '/prd/$slug'
      fullPath: '/prd/$slug'
      preLoaderRoute: typeof PrdSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hpanel/submissions': {
      id: '/hpanel/submissions'
      path: '/submissions'
      fullPath: '/hpanel/submissions'
      preLoaderRoute: typeof HpanelSubmissionsRouteImport
      parentRoute: typeof HpanelRoute
    }
    '/hpanel/skills': {
      id: '/hpanel/skills'
      path: '/skills'
      fullPath: '/hpanel/skills'
      preLoaderRoute: typeof HpanelSkillsRouteImport
      parentRoute: typeof HpanelRoute
    }
    '/hpanel/settings': {
      id: '/hpanel/settings'
      path: '/settings'
      fullPath: '/hpanel/settings'
      preLoaderRoute: typeof HpanelSettingsRouteImport
      parentRoute: typeof HpanelRoute
    }
    '/hpanel/repos': {
      id: '/hpanel/repos'
      path: '/repos'
      fullPath: '/hpanel/repos'
      preLoaderRoute: typeof HpanelReposRouteImport
      parentRoute: typeof HpanelRoute
    }
    '/hpanel/prompts': {
      id: '/hpanel/prompts'
      path: '/prompts'
      fullPath: '/hpanel/prompts'
      preLoaderRoute: typeof HpanelPromptsRouteImport
      parentRoute: typeof HpanelRoute
    }
    '/hpanel/prompt-categories': {
      id: '/hpanel/prompt-categories'
      path: '/prompt-categories'
      fullPath: '/hpanel/prompt-categories'
      preLoaderRoute: typeof HpanelPromptCategoriesRouteImport
      parentRoute: typeof HpanelRoute
    }
    '/hpanel/prds': {
      id: '/hpanel/prds'
      path: '/prds'
      fullPath: '/hpanel/prds'
      preLoaderRoute: typeof HpanelPrdsRouteImport
      parentRoute: typeof HpanelRoute
    }
    '/hpanel/prd-categories': {
      id: '/hpanel/prd-categories'
      path: '/prd-categories'
      fullPath: '/hpanel/prd-categories'
      preLoaderRoute: typeof HpanelPrdCategoriesRouteImport
      parentRoute: typeof HpanelRoute
    }
    '/hpanel/owners': {
      id: '/hpanel/owners'
      path: '/owners'
      fullPath: '/hpanel/owners'
      preLoaderRoute: typeof HpanelOwnersRouteImport
      parentRoute: typeof HpanelRoute
    }
    '/hpanel/import': {
      id: '/hpanel/import'
      path: '/import'
      fullPath: '/hpanel/import'
      preLoaderRoute: typeof HpanelImportRouteImport
      parentRoute: typeof HpanelRoute
    }
    '/hpanel/docs': {
      id: '/hpanel/docs'
      path: '/docs'
      fullPath: '/hpanel/docs'
      preLoaderRoute: typeof HpanelDocsRouteImport
      parentRoute: typeof HpanelRoute
    }
    '/hpanel/categories': {
      id: '/hpanel/categories'
      path: '/categories'
      fullPath: '/hpanel/categories'
      preLoaderRoute: typeof HpanelCategoriesRouteImport
      parentRoute: typeof HpanelRoute
    }
    '/hpanel/add': {
      id: '/hpanel/add'
      path: '/add'
      fullPath: '/hpanel/add'
      preLoaderRoute: typeof HpanelAddRouteImport
      parentRoute: typeof HpanelRoute
    }
    '/docs/what-are-skills': {
      id: '/docs/what-are-skills'
      path: '/docs/what-are-skills'
      fullPath: '/docs/what-are-skills'
      preLoaderRoute: typeof DocsWhatAreSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/specification': {
      id: '/docs/specification'
      path: '/docs/specification'
      fullPath: '/docs/specification'
      preLoaderRoute: typeof DocsSpecificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/integrate': {
      id: '/docs/integrate'
      path: '/docs/integrate'
      fullPath: '/docs/integrate'
      preLoaderRoute: typeof DocsIntegrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/create': {
      id: '/docs/create'
      path: '/docs/create'
      fullPath: '/docs/create'
      preLoaderRoute: typeof DocsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$owner/': {
      id: '/skills/$owner/'
      path: '/skills/$owner'
      fullPath: '/skills/$owner/'
      preLoaderRoute: typeof SkillsOwnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/legacy/$skillId': {
      id: '/skills/legacy/$skillId'
      path: '/skills/legacy/$skillId'
      fullPath: '/skills/legacy/$skillId'
      preLoaderRoute: typeof SkillsLegacySkillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hpanel/skill/github-extractor': {
      id: '/hpanel/skill/github-extractor'
      path: '/skill/github-extractor'
      fullPath: '/hpanel/skill/github-extractor'
      preLoaderRoute: typeof HpanelSkillGithubExtractorRouteImport
      parentRoute: typeof HpanelRoute
    }
    '/skills/$owner/$repo/': {
      id: '/skills/$owner/$repo/'
      path: '/skills/$owner/$repo'
      fullPath: '/skills/$owner/$repo/'
      preLoaderRoute: typeof SkillsOwnerRepoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$owner/$repo/$skillSlug': {
      id: '/skills/$owner/$repo/$skillSlug'
      path: '/skills/$owner/$repo/$skillSlug'
      fullPath: '/skills/$owner/$repo/$skillSlug'
      preLoaderRoute: typeof SkillsOwnerRepoSkillSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HpanelRouteChildren {
  HpanelAddRoute: typeof HpanelAddRoute
  HpanelCategoriesRoute: typeof HpanelCategoriesRoute
  HpanelDocsRoute: typeof HpanelDocsRoute
  HpanelImportRoute: typeof HpanelImportRoute
  HpanelOwnersRoute: typeof HpanelOwnersRoute
  HpanelPrdCategoriesRoute: typeof HpanelPrdCategoriesRoute
  HpanelPrdsRoute: typeof HpanelPrdsRoute
  HpanelPromptCategoriesRoute: typeof HpanelPromptCategoriesRoute
  HpanelPromptsRoute: typeof HpanelPromptsRoute
  HpanelReposRoute: typeof HpanelReposRoute
  HpanelSettingsRoute: typeof HpanelSettingsRoute
  HpanelSkillsRoute: typeof HpanelSkillsRoute
  HpanelSubmissionsRoute: typeof HpanelSubmissionsRoute
  HpanelIndexRoute: typeof HpanelIndexRoute
  HpanelSkillGithubExtractorRoute: typeof HpanelSkillGithubExtractorRoute
}

const HpanelRouteChildren: HpanelRouteChildren = {
  HpanelAddRoute: HpanelAddRoute,
  HpanelCategoriesRoute: HpanelCategoriesRoute,
  HpanelDocsRoute: HpanelDocsRoute,
  HpanelImportRoute: HpanelImportRoute,
  HpanelOwnersRoute: HpanelOwnersRoute,
  HpanelPrdCategoriesRoute: HpanelPrdCategoriesRoute,
  HpanelPrdsRoute: HpanelPrdsRoute,
  HpanelPromptCategoriesRoute: HpanelPromptCategoriesRoute,
  HpanelPromptsRoute: HpanelPromptsRoute,
  HpanelReposRoute: HpanelReposRoute,
  HpanelSettingsRoute: HpanelSettingsRoute,
  HpanelSkillsRoute: HpanelSkillsRoute,
  HpanelSubmissionsRoute: HpanelSubmissionsRoute,
  HpanelIndexRoute: HpanelIndexRoute,
  HpanelSkillGithubExtractorRoute: HpanelSkillGithubExtractorRoute,
}

const HpanelRouteWithChildren =
  HpanelRoute._addFileChildren(HpanelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HpanelRoute: HpanelRouteWithChildren,
  PrdsRoute: PrdsRoute,
  PromptsRoute: PromptsRoute,
  SubmitRoute: SubmitRoute,
  DocsCreateRoute: DocsCreateRoute,
  DocsIntegrateRoute: DocsIntegrateRoute,
  DocsSpecificationRoute: DocsSpecificationRoute,
  DocsWhatAreSkillsRoute: DocsWhatAreSkillsRoute,
  PrdSlugRoute: PrdSlugRoute,
  PromptSlugRoute: PromptSlugRoute,
  DocsIndexRoute: DocsIndexRoute,
  SkillsIndexRoute: SkillsIndexRoute,
  SkillsLegacySkillIdRoute: SkillsLegacySkillIdRoute,
  SkillsOwnerIndexRoute: SkillsOwnerIndexRoute,
  SkillsOwnerRepoSkillSlugRoute: SkillsOwnerRepoSkillSlugRoute,
  SkillsOwnerRepoIndexRoute: SkillsOwnerRepoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
